# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e227521bff666a207fabccc55c8042899ec85f15c431b3c21d2841110b6adb38c93d785e3e904d5ad627f67f420a611c40a6837b13a925a9bc692985634784a1

test:
  secret_key_base: 1afe53710ff0d8cc37dc3c11a904b5706378a68f01dedecd62f5a3c62eb00de72093c211c23c7e2ec28d24834622741a7e32dc928ed03fc4817d323476212f6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
